### ISSUE TITLE
Quickshell not working after Qt 6.10 update — rebuild required

### ISSUE THREAD

**Issue by tripathiji1312** [quickshell-mirror/quickshell#301]
## Issue
After updating to Qt 6.10.0, Quickshell no longer works. The following warning appears:
```
WARN: Quickshell was built against Qt 6.9.2 but the system has updated to Qt 6.10.0 without rebuilding the package. This is likely to cause crashes, so the quickshell package must be rebuilt.
```
## System information:
- Distro: `Arch Linux (Hyprland)`
- Qt version: `6.10.0`
- Quickshell version: `0.2.0`
- Install method: `AUR (package: quickshell)`

**Comment by Gashmob** [comment]
Have the same issue, and when running `yay -S --rebuild quickshell` I got many compile error of this type:

```
CMake Error at src/wayland/CMakeLists.txt:69 (target_link_libraries):
  Target "wlp-hyprland-surface" links to:

    Qt6::WaylandClientPrivate

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  src/wayland/hyprland/surface/CMakeLists.txt:15 (wl_proto)
```

**Comment by tripathiji1312** [comment]
@Gashmob Exactly same for me, it was okay before but after system update this issue was started.

**Comment by AkiraLyu** [comment]
This issue has been fixed but not yet released. As a workaround, you can use the AUR package `quickshell-git` instead of `quickshell`.

**Comment by alerque** [comment]
I'm an Arch Linux package manager and have been working towards getting quickshell packaged in official repos (as a dependency for dms). If this project doesn't keep up with Qt releases though that is going to be a bit of a problem for me. In this case it would mean having to backport patches so as not to hold the whole distro up.

Is this a regular issue with Qt releases? Will the project be trying to get the fix for this released ASAP?

**Comment by outfoxxed** [comment]
I generally check for breakage in new minor qt releases once release candidates start getting pushed. In this case breakage was fixed last week in the master branch. I was not aware that arch had already pushed 6.10, and plan to make another release today.

> Is this a regular issue with Qt releases?

We're forced to depend on a lot of private Qt apis so things break occasionally.

**Comment by outfoxxed** [comment]
I've released 0.2.1 with the fix.

**Comment by alerque** [comment]
Thanks for pushing the fix as a release, and thank you also for the background information. That's helpful to know.

I'm on the road right now and it might take a week or two to cleanup all the packaging including dependencies, but I'm part way there and it look like it's going to work, so official Arch packages should be along in the future.

**Comment by outfoxxed** [comment]
Good to hear. Note that with 6.10, QtWaylandClient is part of QtBase, so you can drop the qtwayland dependency (which is now just QtWaylandCompositor)

**Comment by ambrosia13** [comment]
I still have build issues with the new quickshell update (same package). I tried rebuilding `google-breakpad`, but it didn't fix it. This is all after running `pacman -Syu` for a system upgrade.

```
~ ❯ quickshell --version
quickshell 0.2.0, revision 704925ffbfc95040845047f69d31ccb038eabf65, distributed by: AUR (package: quickshell)
```

Trying to upgrade quickshell with `yay -S quickshell` gives a lot of CMAKE errors as pointed out earlier, here is the full log: 

{redacted#42583163}

(Sorry if I did anything wrong here, I'm quite new to arch-based systems)

**Comment by alerque** [comment]
@ambrosia13 The current AUR packaging for quickshell (not maintained by me) is badly setup and just bumping the package version won't build the new sources. You can try using the prebuilt packages in my Arch user repository for now until I get them migrated to official repos, I think everything is working if you use the packages from there. See the Arch Wiki page on user repositories to find the address to mine.
